export const WecomeText1 = '"Glad to have you here again today.'
export const WecomeText2 = 'Let s do some journaling together for today!'
export const TabMenu1 = 'Home'
export const TabMenu2 = 'Journaling'
export const TabMenu3 = 'feedback'
export const TabMenu4 = 'logout'