export const WecomeText1 = '오늘도 와주셔서 반가워요'
export const WecomeText2 = '오늘 하루를 함께 기록해봐요'
export const TabMenu1 = 'Home'
export const TabMenu2 = 'Journaling'
export const TabMenu3 = 'feedback'
export const TabMenu4 = 'logout'